### ISSUE TITLE
Warn user about large buffer size

### ISSUE THREAD

**Issue by McTwist** [McTwist/Support_EventScript#3]
TorqueEngine have problem with echoing strings larger than 4095. It can still handle an unlimited size on the strings.

Add a warning right before creating ends, telling the user when size of string is bigger than 4095 that they should not echo the output.

**Comment by rv32ima** [comment]
Hi this is an issue I have insight on
It occurs due to a buffer overflow from dsprintf ignoring the requested max buffer size and instead copies the entirety of the input buffer to the output buffer
You can’t fix this- it’s been fixed in later versions of the tork engine but sadly Badspot hasn’t applied the fix :(

**Comment by McTwist** [comment]
I am well aware of this issue and I made a fix for it yesterday:
https://gist.github.com/McTwist/1606d73d96e990874941ab6c4a608dec
It's not perfect, but works as `echo` does as long as each line is shorter than 4096 characters.

But according to that last information that it has been fixed and Badspot wont apply it, I will keep the `wontfix` tag and close this.
